version: '3.3'
services:

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wildfly
    volumes:
      - /usr/local/docker-config/httpd/htdocs/picsureui/settings:/usr/local/apache2/htdocs/picsureui/settings
      - /usr/local/docker-config/httpd/htdocs/psamaui/settings:/usr/local/apache2/htdocs/psamaui/settings
      - /usr/local/docker-config/httpd/htdocs/static:/usr/local/apache2/htdocs/static
      - /usr/local/docker-config/httpd/cert:/usr/local/apache2/cert
      - ./config/tools:/var/tmp/tools
      - /usr/local/docker-config:/var/tmp/config
    networks:
      - public

  transmart:
    image: dbmi/i2b2transmart:pre_19.1-M1_release.1fed3dc91f
    restart: always
    volumes:
      - /usr/local/docker-config/transmart/transmartConfig:/root/.grails/transmartConfig:rw
      - /usr/local/docker-config/transmart/logs:/usr/local/tomcat/logs:rw
    networks:
      - public
    expose:
      - 8080

  wildfly:
    image: jboss/wildfly:17.0.0.Final
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx2g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    environment:
      - RESULT_FORMAT=JSON
      - IRCT_TARGET_URL=http://httpd/irct
    expose:
      - 8080
    ports:
      - 8787:8787
    networks:
      - public
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug 0.0.0.0:8787
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/modules/system/layers/base/com/sql/:/opt/jboss/wildfly/modules/system/layers/base/com/sql/
      - /usr/local/docker-config/wildfly/modules/system/layers/base/com/oracle/:/opt/jboss/wildfly/modules/system/layers/base/com/oracle/
      - /usr/local/docker-config/wildfly/deployments/:/opt/jboss/wildfly/standalone/deployments/
      - /usr/local/docker-config/wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - /usr/local/docker-config/wildfly/resources/activation.mustache:/opt/jboss/wildfly/standalone/configuration/activation.mustache
    depends_on:
      - copy-pic-sure-war
      - copy-pic-sure-auth-war
      - copy-pic-sure-irct-resource

  copy-pic-sure-war:
    image: dbmi/picsure2:picsure283.ee6ce0a
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-api-2.war /var/tmp/pic-sure-api-2.war

  copy-pic-sure-irct-resource:
    image: dbmi/pic-sure-irct-resource:picsure310.ef69613
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-irct-resource.war /var/tmp/pic-sure-irct-resource.war

  copy-pic-sure-auth-war:
    image: dbmi/pic-sure-auth-services:fence-integration_72ef997e3346
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-auth-services.war /var/tmp/pic-sure-auth-services.war

networks:
  public:
