version: '3.3'
services:

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - /usr/local/docker-conf/httpd/htdocs/picsureui/settings:/usr/local/apache2/htdocs/picsureui/settings
      - /usr/local/docker-conf/httpd/htdocs/admin/settings:/usr/local/apache2/htdocs/admin/settings
    networks:
      - public

  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    depends_on:
      - rserve
    volumes:
      - /usr/local/docker-conf/transmart/transmartConfig:/root/.grails/transmartConfig
      - rserve-jobs:/tmp:rw
    networks:
      - public
    expose:
      - 8080

  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    expose:
      - 6311
    volumes:
      - rserve-jobs:/tmp:rw
    networks:
      - public

  irct:
    image: dbmi/irct:${irct_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - i2b2-wildfly
      - picsure-db
    restart: always
    networks:
      - public
    expose:
      - 8080

  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    networks:
      - public
    expose:
      - 9090

  picsure2:
    image: dbmi/picsure2:${picsure2_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - picsure-db
    restart: always
    expose:
      - 8080
    command: --server-config=standalone.xml
    networks:
      - public

  picsure-db:
    image: dbmi/auth-db:5.7.22_initial_schema
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    expose:
      - 3306
    volumes:
      - picsure-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_MYSQL_ROOT_PASSWORD:-password}
    networks:
      - public

  picsureauth:
    image: dbmi/pic-sure-auth-services:Jan-29-2019
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - picsure-db
    expose:
      - 8080
    networks:
      - public

  nhaneshpds:
    image: dbmi/pic-sure-hpds-nhanes:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    env_file: .env
    networks:
      - public
    expose:
      - 8080

volumes:
  picsure-db:
  # shared volume for R jobs
  rserve-jobs:

networks:
  public:
