version: '3.3'
services:

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - psama
      - picsure
    volumes:
      - /usr/local/docker-config/httpd/htdocs/picsureui/settings:/usr/local/apache2/htdocs/picsureui/settings
      - /usr/local/docker-config/httpd/htdocs/psamaui/settings:/usr/local/apache2/htdocs/psamaui/settings
    networks:
      - public

  transmart:
    image: dbmi/i2b2transmart:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    volumes:
      - /usr/local/docker-config/transmart/transmartConfig:/root/.grails/transmartConfig:rw
    networks:
      - public
    expose:
      - 8080

  solr:
    image: dbmi/solr:4.5.0-tm.release-18.1
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    networks:
      - public
    expose:
      - 8983
    ports:
      - 8983:8983

  fractalis:
    image: sherzinger/fractalis:1.3.1
    environment:
      - FRACTALIS_CONFIG=/config.py
    volumes:
      - /usr/local/docker-config/fractalis/config.py:/config.py
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    command: gunicorn -w 3 -b :5000 --timeout 90 --log-file - fractalis:app
    networks:
      - public
    expose:
      - 5000
    restart: always
    depends_on:
      - irct
      - redis
      - rabbitmq
      - worker

  worker:
    image: sherzinger/fractalis:1.3.1
    environment:
      - FRACTALIS_CONFIG=/config.py
    volumes:
      - /usr/local/docker-config/fractalis/config.py:/config.py
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    command: celery worker -A fractalis:celery -l info --autoscale 16,4
    networks:
      - public
    restart: always
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    command: >
      sh -c "redis-server
      && redis-cli CONFIG SET maxmemory 4gb
      && redis-cli CONFIG SET maxmemory-policy allkeys-lru
      && redis-cli CONFIG SET save ''
      && redis-cli CONFIG SET appendonly no"
    networks:
      - public

  rabbitmq:
    image: rabbitmq:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    networks:
      - public

  irct:
    image: dbmi/irct:master_72135ce
    volumes:
      - /usr/local/docker-config/irct/wildfly/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    depends_on:
      - i2b2-wildfly
    restart: always
    networks:
      - public
    expose:
      - 8080

  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:1.7.09c-18.1-beta-hotfix
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    volumes:
      - /usr/local/docker-config/i2b2-wildfly/wildfly/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    restart: always
    networks:
      - public
    expose:
      - 9090

  picsure:
    image: dbmi/picsure2:picsure246-jndi.7c32223
    volumes:
      - /usr/local/docker-config/picsure/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
      - /usr/local/docker-config/picsure/standalone/deployments/pic-sure-irct-resource.war:/opt/jboss/wildfly/standalone/deployments/pic-sure-irct-resource.war:rw
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    environment:
      - RESULT_FORMAT=json
      - IRCT_TARGET_URL=http://httpd/irct
    restart: always
    depends_on:
      - copy-irct-resource
    expose:
      - 8080
    networks:
      - public

  copy-irct-resource:
    image: dbmi/pic-sure-irct-resource:picsure246-jndi.ea3c615_jason
    user: root
    volumes:
      - /usr/local/docker-config/picsure/standalone/deployments:/tmp/deployments
    networks:
      - public
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-irct-resource.war /tmp/deployments/pic-sure-irct-resource.war

  pic-sure-auth:
    image: dbmi/pic-sure-auth-services:master.2839b24
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
    volumes:
      - /usr/local/docker-config/psama/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    expose:
      - 8080
    networks:
      - public

networks:
  public:
