version: '3.3'
services:

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - /usr/local/docker-conf/httpd/htdocs/picsureui/settings:/usr/local/apache2/htdocs/picsureui/settings
      - /usr/local/docker-conf/httpd/htdocs/psamaui/settings/:/usr/local/apache2/htdocs/psamaui/settings/
    networks:
      - public

  transmart:
    image: dbmi/i2b2transmart:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    depends_on:
      - rserve
    volumes:
      - /usr/local/docker-conf/transmart/transmartConfig:/root/.grails/transmartConfig
      - rserve-jobs:/tmp:rw
    networks:
      - public
    expose:
      - 8080

  rserve:
    image: dbmi/rserve:3.2.1-tm.release-18.1
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    expose:
      - 6311
    volumes:
      - rserve-jobs:/tmp:rw
    networks:
      - public

  solr:
    image: dbmi/solr:4.5.0-tm.release-18.1
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file: .env
    restart: always
    networks:
      - public
    expose:
      - 8983
    ports:
      - 8983:8983

  fractalis:
    image: sherzinger/fractalis:1.3.1
    volumes:
      - /usr/local/docker-conf/fractalis/config.py:/config.py
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    environment:
      - FRACTALIS_CONFIG=/config.py
    command: gunicorn -w 3 -b :5000 --timeout 90 --log-file - fractalis:app
    networks:
      - public
    expose:
      - 5000
    restart: always
    depends_on:
      - irct
      - redis
      - rabbitmq
      - worker

  worker:
    image: sherzinger/fractalis:1.3.1
    volumes:
      - /usr/local/docker-conf/fractalis/config.py:/config.py
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    environment:
      - FRACTALIS_CONFIG=/config.py
    command: celery worker -A fractalis:celery -l info --autoscale 16,4
    networks:
      - public
    restart: always
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    command: >
      sh -c "redis-server
      && redis-cli CONFIG SET maxmemory 4gb
      && redis-cli CONFIG SET maxmemory-policy allkeys-lru
      && redis-cli CONFIG SET save ''
      && redis-cli CONFIG SET appendonly no"
    networks:
      - public

  rabbitmq:
    image: rabbitmq:alpine
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - public

  irct:
    image: dbmi/irct:1.4.2c
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - i2b2-wildfly
      - picsure-db
    restart: always
    networks:
      - public
    expose:
      - 8080

  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:1.7.09c-18.1-beta-hotfix
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    networks:
      - public
    expose:
      - 9090

  picsure:
    image: dbmi/picsure2:0.0.0.irct_included2
    volumes:
      - /usr/local/docker-conf/picsure/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - picsure-db
    restart: always
    expose:
      - 8080
    command: --server-config=standalone.xml
    networks:
      - public

  picsure-db:
    image: dbmi/psama-db:3dea3ede
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_MYSQL_ROOT_PASSWORD:-password}
    networks:
      - public

  psama:
    image: dbmi/psama:3dea3ede
    env_file: .env
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - picsure-db
    volumes:
      - /usr/local/docker-conf/picsureauth/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    expose:
      - 8080
    networks:
      - public

  hpds:
    image: dbmi/pic-sure-hpds-nhanes:18.1-Quickstart
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    env_file: .env
    networks:
      - public
    expose:
      - 8080

volumes:
  # shared volume for R jobs
  rserve-jobs:

networks:
  public:
