version: '3.3'
services:
	
	initdb:
		build:
			context: ./config/tools
			dockerfile: Dockerfile.initdb
			environment:
				- MYSQL_ROOT_PASSWORD=password
				- RDS_MYSQL_PASSWORD=from_command_line_mysql_root_password
				- RDS_MYSQL_HOST=from_command_line_mysql_host

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wildfly
    volumes:
      - /usr/local/docker-config/httpd/htdocs/picsureui/settings:/usr/local/apache2/htdocs/picsureui/settings
      - /usr/local/docker-config/httpd/htdocs/psamaui/settings:/usr/local/apache2/htdocs/psamaui/settings
      - /usr/local/docker-config/httpd/htdocs/static:/usr/local/apache2/htdocs/static
      - /usr/local/docker-config/httpd/cert:/usr/local/apache2/cert
    networks:
      - public

  transmart:
    image: dbmi/i2b2transmart:pre_19.1-M1_release.1fed3dc91f
    restart: always
    volumes:
      - /usr/local/docker-config/transmart/transmartConfig:/root/.grails/transmartConfig:rw
      - /usr/local/docker-config/transmart/logs:/usr/local/tomcat/logs:rw
    networks:
      - public
    expose:
      - 8080

  solr:
    image: dbmi/solr:4.5.0-tm.release-18.1
    restart: always
    networks:
      - public
    expose:
      - 8983
    ports:
      - 8983:8983

  fractalis:
    image: dbmi/fractalis:1.3.1-quickstart-hotfix
    environment:
      - FRACTALIS_CONFIG=/config.py
    volumes:
      - /usr/local/docker-config/fractalis/config.py:/config.py
    restart: always
    command: gunicorn -w 3 -b :5000 --timeout 90 --log-file - fractalis:app
    networks:
      - public
    expose:
      - 5000
    restart: always
    depends_on:
      - redis
      - rabbitmq
      - worker

  worker:
    image: dbmi/fractalis:1.3.1-quickstart-hotfix
    environment:
      - FRACTALIS_CONFIG=/config.py
    volumes:
      - /usr/local/docker-config/fractalis/config.py:/config.py
    restart: always
    command: celery worker -A fractalis:celery -l info --autoscale 16,4
    networks:
      - public
    restart: always
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    restart: always
    command: >
      sh -c "redis-server
      && redis-cli CONFIG SET maxmemory 4gb
      && redis-cli CONFIG SET maxmemory-policy allkeys-lru
      && redis-cli CONFIG SET save ''
      && redis-cli CONFIG SET appendonly no"
    networks:
      - public

  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    networks:
      - public

  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:1.7.09c-18.1-beta-hotfix
    environment:
      - JAVA_OPTS=-XX:SurvivorRatio=255 -Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    volumes:
      - /usr/local/docker-config/i2b2-wildfly/wildfly/standalone/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw
    restart: always
    networks:
      - public
    expose:
      - 9090

  irct:
    image: dbmi/irct:master_72135ce
    networks:
      - public
    user: root
    expose:
      - 8080
      - 8787
    ports:
      - 8081:8080
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    volumes:
      - /usr/local/docker-config/irct/scratch:/scratch/irct:rw
      - /usr/local/docker-config/irct/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:rw

  wildfly:
    image: jboss/wildfly:17.0.0.Final
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx2g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    restart: always
    environment:
      - RESULT_FORMAT=JSON
      - IRCT_TARGET_URL=http://httpd/irct
    expose:
      - 8080
    ports:
      - 8787:8787
    networks:
      - public
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug 0.0.0.0:8787
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/modules/system/layers/base/com/sql/:/opt/jboss/wildfly/modules/system/layers/base/com/sql/
      - /usr/local/docker-config/wildfly/modules/system/layers/base/com/oracle/:/opt/jboss/wildfly/modules/system/layers/base/com/oracle/
      - /usr/local/docker-config/wildfly/deployments/:/opt/jboss/wildfly/standalone/deployments/
      - /usr/local/docker-config/wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - /usr/local/docker-config/wildfly/resources/activation.mustache:/opt/jboss/wildfly/standalone/configuration/activation.mustache
    depends_on:
      - copy-pic-sure-war
      - copy-pic-sure-auth-war
      - copy-pic-sure-irct-resource

  copy-pic-sure-war:
    image: dbmi/picsure2:picsure283.ee6ce0a
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-api-2.war /var/tmp/pic-sure-api-2.war

  copy-pic-sure-irct-resource:
    image: dbmi/pic-sure-irct-resource:picsure310.ef69613
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-irct-resource.war /var/tmp/pic-sure-irct-resource.war

  copy-pic-sure-auth-war:
    image: dbmi/pic-sure-auth-services:master.bcf79f9
    user: root
    volumes:
      - /usr/local/docker-config/wildfly/deployments:/var/tmp
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-auth-services.war /var/tmp/pic-sure-auth-services.war

networks:
  public:
